import { IMG } from "./media";

export type Traveller =
  | "Family"
  | "Couples"
  | "Honeymoon"
  | "Senior Citizens"
  | "Friends"
  | "Corporate";

export interface Attraction {
  name: string;
  desc: string;
}

export interface FaqItem {
  q: string;
  a: string;
}

export interface Destination {
  slug: string;
  name: string;
  country: string;
  region: "international" | "domestic";
  prime?: boolean;
  ribbon?: string;
  tagline: string;
  hero: string;
  gallery: string[];
  overview: string;
  whyVisit: string[];
  bestTime: string;
  bestTimeNote: string;
  idealFor: Traveller[];
  attractions: Attraction[];
  experiences: string[];
  visa?: string;
  hotels: string[];
  faqs?: FaqItem[];
  related?: string[];
}

const baseFaqs = (d: Omit<Destination, "faqs">): FaqItem[] => [
  {
    q: `What is the best time to visit ${d.name}?`,
    a: `${d.bestTimeNote} Our travel designers will align your dates with festivals, weather windows and family schedules before confirming anything.`,
  },
  {
    q: `Is ${d.name} suitable for families and senior citizens?`,
    a: `Yes. Every ${d.name} journey we plan is paced to the guests travelling — ${d.idealFor.join(
      ", ",
    )} all travel with us. We adjust walking distances, drive times, room categories and meal preferences accordingly.`,
  },
  d.region === "international"
    ? {
        q: `What are the visa requirements for ${d.name}?`,
        a: `${d.visa ?? "Visa requirements vary by nationality and travel purpose."} Our documentation desk shares an accurate, up-to-date checklist and assists with the application — we never guarantee an outcome, as approvals rest solely with the issuing authority.`,
      }
    : {
        q: `Do you arrange flights, trains and transfers within India for ${d.name}?`,
        a: `Yes. Domestic flights, premium rail, private chauffeur-driven vehicles and airport meet-and-greet are all arranged as part of your itinerary.`,
      },
  {
    q: `How do I get a customised ${d.name} itinerary?`,
    a: `Share your dates, group size and travel style through the enquiry form or WhatsApp. A dedicated travel expert responds with a personalised plan — we do not publish fixed packages or prices because every journey is designed from scratch.`,
  },
];

const make = (d: Omit<Destination, "faqs"> & { faqs?: FaqItem[] }): Destination => ({
  ...d,
  faqs: [...(d.faqs ?? []), ...baseFaqs(d)].slice(0, 6),
});

export const destinations: Destination[] = [
  /* ────────────────  PRIME GROUP DESTINATIONS  ──────────────── */
  make({
    slug: "dubai",
    name: "Dubai",
    country: "United Arab Emirates",
    region: "international",
    prime: true,
    ribbon: "Most Popular Group Tours",
    tagline: "Where desert gold meets skyline silver",
    hero: IMG.dubai1,
    gallery: [IMG.dubai2, IMG.dubai5, IMG.dubai3, IMG.dubai4],
    overview:
      "Dubai is the effortless first passport stamp — a city where a Burj Khalifa sunset, a golden desert evening and a marina yacht brunch fit comfortably into a single long weekend. Superb connectivity from Jodhpur, Jaipur and Delhi, world-class hotels and genuinely family-friendly attractions make it our most requested group destination.",
    whyVisit: [
      "Short flying time with excellent connections from India",
      "Iconic skyline, beaches and desert within one compact city",
      "Outstanding shopping, dining and entertainment for every age",
      "Seamless infrastructure ideal for large families and corporate groups",
    ],
    bestTime: "October – April",
    bestTimeNote:
      "October to April brings warm days and cool evenings — perfect for desert safaris, cruises and outdoor dining.",
    idealFor: ["Family", "Couples", "Honeymoon", "Senior Citizens", "Friends", "Corporate"],
    attractions: [
      { name: "Burj Khalifa & Dubai Fountain", desc: "Sunset access to levels 124/148 with the fountain show below." },
      { name: "Desert Safari & Al Marmoom", desc: "Dune drives, falconry and a private Bedouin-style dinner under the stars." },
      { name: "Palm Jumeirah & Atlantis", desc: "Monorail views, The View at The Palm and aquatic adventures." },
      { name: "Old Dubai & Al Fahidi", desc: "Abra ride across the creek, gold and spice souks, Emirati coffee houses." },
    ],
    experiences: [
      "Private yacht charter along Dubai Marina",
      "Hot air balloon over the Al Marmoom desert",
      "Michelin-recognised dining and dhow dinner cruise",
      "Corporate offsites at Expo City and DWTC",
      "Day trip to Abu Dhabi's Sheikh Zayed Grand Mosque",
    ],
    visa: "Indian passport holders require a UAE tourist visa (commonly 14, 30 or 60 days).",
    hotels: [
      "Beachfront resorts on JBR and Palm Jumeirah",
      "Downtown five-star hotels with Burj Khalifa views",
      "Family suites and connecting rooms in Deira & Bur Dubai",
    ],
    related: ["singapore", "thailand", "azerbaijan"],
  }),
  make({
    slug: "vietnam",
    name: "Vietnam",
    country: "Vietnam",
    region: "international",
    prime: true,
    ribbon: "Most Popular Group Tours",
    tagline: "Emerald bays, lantern-lit lanes and endless green",
    hero: IMG.vn2,
    gallery: [IMG.vn6, IMG.vn1, IMG.vn3, IMG.vn5],
    overview:
      "Vietnam rewards travellers with extraordinary variety — the limestone drama of Ha Long Bay, the lantern glow of Hoi An, the terraced highlands of the north and the beach resorts of Da Nang and Phu Quoc. It is exceptional value at a luxury standard, which is why our group departures fill quickly.",
    whyVisit: [
      "UNESCO cruising in Ha Long and Lan Ha Bay",
      "Rich heritage towns, cuisine and coffee culture",
      "Superb beach resorts along the central coast",
      "Comfortable, affordable luxury for larger groups",
    ],
    bestTime: "November – April",
    bestTimeNote:
      "November to April offers dry, pleasant weather across the north and central regions; the south is enjoyable year-round.",
    idealFor: ["Family", "Couples", "Honeymoon", "Senior Citizens", "Friends", "Corporate"],
    attractions: [
      { name: "Ha Long / Lan Ha Bay", desc: "Overnight cruise among thousands of limestone karsts." },
      { name: "Hoi An Ancient Town", desc: "Silk lanterns, tailors, riverside dining and bicycle lanes." },
      { name: "Ba Na Hills & Golden Bridge", desc: "Cable-car ascent to the famous stone hands and French village." },
      { name: "Ninh Binh & Trang An", desc: "Sampan rowing through caves and rice-field valleys." },
    ],
    experiences: [
      "Overnight luxury junk cruise with private balcony cabins",
      "Hoi An lantern-making and street-food walk",
      "Mekong Delta sampan and floating market morning",
      "Cyclo heritage tour of Hanoi's Old Quarter",
      "Beach days in Da Nang, Nha Trang or Phu Quoc",
    ],
    visa: "An e-visa is available for Indian passport holders; validity and entry type vary.",
    hotels: [
      "Beach resorts in Da Nang and Phu Quoc",
      "Heritage boutique stays in Hoi An",
      "Contemporary five-star hotels in Hanoi & Ho Chi Minh City",
    ],
    related: ["thailand", "bali", "singapore"],
  }),
  make({
    slug: "bali",
    name: "Bali",
    country: "Indonesia",
    region: "international",
    prime: true,
    ribbon: "Most Popular Group Tours",
    tagline: "The island of temples, rice terraces and slow luxury",
    hero: IMG.bali2,
    gallery: [IMG.bali1, IMG.bali4, IMG.bali5, IMG.bali3],
    overview:
      "Bali blends spiritual calm with barefoot luxury. Cliff-edge villas in Uluwatu, jungle pools in Ubud and the white sand of Nusa Dua make it our most requested honeymoon island — and a surprisingly wonderful multi-generational family destination.",
    whyVisit: [
      "World-renowned private pool villas and wellness resorts",
      "Temples, rice terraces and volcano sunrises",
      "Island-hopping to Nusa Penida and Gili Islands",
      "Excellent value for premium honeymoon inclusions",
    ],
    bestTime: "April – October",
    bestTimeNote: "April to October is the dry season with sunny days and lower humidity.",
    idealFor: ["Couples", "Honeymoon", "Family", "Friends", "Corporate"],
    attractions: [
      { name: "Uluwatu Temple", desc: "Clifftop sunset temple with the traditional Kecak fire dance." },
      { name: "Tegallalang Rice Terraces", desc: "Sculpted emerald valleys and jungle swings above Ubud." },
      { name: "Nusa Penida", desc: "Kelingking cliff, Broken Beach and Angel's Billabong day cruise." },
      { name: "Tanah Lot", desc: "Sea temple silhouetted against the Indian Ocean at dusk." },
    ],
    experiences: [
      "Private pool villa with floating breakfast",
      "Balinese blessing ceremony and spa ritual",
      "Mount Batur sunrise trek or jeep sunrise tour",
      "Romantic candlelit dinner on Jimbaran Beach",
      "Catamaran cruise to the Gili Islands",
    ],
    visa: "Visa on arrival is available for Indian passport holders at major Indonesian airports.",
    hotels: [
      "Private pool villas in Seminyak & Ubud",
      "Clifftop luxury resorts in Uluwatu",
      "Family beach resorts in Nusa Dua",
    ],
    related: ["thailand", "vietnam", "maldives"],
  }),
  make({
    slug: "singapore",
    name: "Singapore",
    country: "Singapore",
    region: "international",
    prime: true,
    ribbon: "Most Popular Group Tours",
    tagline: "A garden city engineered for wonder",
    hero: IMG.sg3,
    gallery: [IMG.sg4, IMG.sg6, IMG.sg1, IMG.sg5],
    overview:
      "Singapore is precision-planned delight: Gardens by the Bay after dark, Sentosa for the children, Marina Bay for the skyline and hawker centres for the food. Clean, safe, walkable and entirely English-friendly, it is the easiest first international holiday for Indian families and senior citizens.",
    whyVisit: [
      "Impeccably safe and easy to navigate",
      "Universal Studios and Sentosa for families",
      "Extraordinary food, from hawker stalls to fine dining",
      "Effortless twin-centre pairing with Malaysia or Bali",
    ],
    bestTime: "Year-round",
    bestTimeNote:
      "Singapore is a year-round destination; February to April is the driest and most comfortable window.",
    idealFor: ["Family", "Couples", "Honeymoon", "Senior Citizens", "Friends", "Corporate"],
    attractions: [
      { name: "Gardens by the Bay", desc: "Supertree Grove light show, Cloud Forest and Flower Dome." },
      { name: "Sentosa & Universal Studios", desc: "Theme park thrills, S.E.A. Aquarium and beach clubs." },
      { name: "Marina Bay Sands SkyPark", desc: "Panoramic observation deck above the bay." },
      { name: "Singapore Zoo & Night Safari", desc: "Among the world's finest open-concept wildlife parks." },
    ],
    experiences: [
      "Night Safari tram with a private guide",
      "Singapore Flyer sunset capsule",
      "Little India, Chinatown and Kampong Glam heritage walk",
      "Corporate MICE venues at Marina Bay & Suntec",
      "Jewel Changi Rain Vortex stopover",
    ],
    visa: "Indian passport holders require a Singapore tourist visa applied through authorised channels.",
    hotels: [
      "Iconic Marina Bay landmark hotels",
      "Family-friendly resorts on Sentosa Island",
      "Boutique heritage stays in Chinatown & Katong",
    ],
    related: ["malaysia", "thailand", "hong-kong"],
  }),
  make({
    slug: "thailand",
    name: "Thailand",
    country: "Thailand",
    region: "international",
    prime: true,
    ribbon: "Most Popular Group Tours",
    tagline: "Turquoise bays, gilded temples, gracious hospitality",
    hero: IMG.th3,
    gallery: [IMG.th4, IMG.th1, IMG.th2, IMG.res6],
    overview:
      "Thailand is the perfect balance of beach, culture and celebration. Bangkok's temples and rooftops, Phuket and Krabi's limestone bays, Koh Samui's serenity and Chiang Mai's mountain calm combine into itineraries that suit honeymooners, families and friends equally.",
    whyVisit: [
      "Some of Asia's finest beaches and island cruises",
      "Exceptional value luxury resorts and spas",
      "Great vegetarian and Indian dining availability",
      "Direct flights and simple travel logistics",
    ],
    bestTime: "November – March",
    bestTimeNote: "November to March delivers clear skies, calm seas and ideal island-hopping conditions.",
    idealFor: ["Family", "Couples", "Honeymoon", "Senior Citizens", "Friends", "Corporate"],
    attractions: [
      { name: "Phi Phi & Maya Bay", desc: "Speedboat or catamaran cruise through emerald lagoons." },
      { name: "Grand Palace & Wat Arun", desc: "Bangkok's gilded royal heart and riverside temple." },
      { name: "James Bond Island, Phang Nga", desc: "Sea-canoe through caves and hidden lagoons." },
      { name: "Chiang Mai & Doi Suthep", desc: "Mountain temples, night bazaars and ethical elephant sanctuaries." },
    ],
    experiences: [
      "Private long-tail island cruise with beach picnic",
      "Chao Phraya luxury dinner cruise",
      "Thai cooking class and floating market morning",
      "Wellness and spa retreat in Koh Samui",
      "Group celebration dinners and MICE venues in Pattaya",
    ],
    visa: "Entry requirements for Indian passport holders vary; our desk confirms the current policy before booking.",
    hotels: [
      "Beachfront resorts in Phuket, Krabi and Koh Samui",
      "Riverside luxury hotels in Bangkok",
      "Boutique lanna-style stays in Chiang Mai",
    ],
    related: ["vietnam", "bali", "malaysia"],
  }),
  make({
    slug: "malaysia",
    name: "Malaysia",
    country: "Malaysia",
    region: "international",
    prime: true,
    ribbon: "Most Popular Group Tours",
    tagline: "Rainforest, islands and skyline in one journey",
    hero: IMG.res4,
    gallery: [IMG.sg1, IMG.th2, IMG.bali5, IMG.res5],
    overview:
      "Malaysia layers the Petronas Towers, the cool highlands of Genting and Cameron, the beaches of Langkawi and the heritage streets of Penang into one comfortable, excellent-value itinerary — and pairs beautifully with Singapore for a two-country holiday.",
    whyVisit: [
      "Twin-centre value with Singapore or Thailand",
      "Halal and Indian food widely available",
      "Langkawi cable car, islands and duty-free shopping",
      "Comfortable climate in the highlands for senior travellers",
    ],
    bestTime: "December – April",
    bestTimeNote:
      "December to April is ideal for the west coast and Langkawi; highlands are pleasant throughout the year.",
    idealFor: ["Family", "Couples", "Honeymoon", "Senior Citizens", "Friends", "Corporate"],
    attractions: [
      { name: "Petronas Twin Towers", desc: "Skybridge and observation deck over Kuala Lumpur." },
      { name: "Langkawi SkyCab & Sky Bridge", desc: "Rainforest cable car with Andaman Sea panoramas." },
      { name: "Batu Caves", desc: "Rainbow steps to a dramatic limestone temple cavern." },
      { name: "Penang George Town", desc: "UNESCO street art, clan houses and celebrated food streets." },
    ],
    experiences: [
      "Island-hopping cruise around Langkawi",
      "Cameron Highlands tea estate morning",
      "KL food trail and Jalan Alor evening",
      "Genting Highlands entertainment day",
      "Mangrove kayak and eagle-watching safari",
    ],
    visa: "Indian passport holders may travel visa-free for short stays under current Malaysian policy — always reconfirmed before departure.",
    hotels: [
      "City-view five-star hotels in Kuala Lumpur",
      "Beach resorts in Langkawi",
      "Heritage boutique hotels in Penang",
    ],
    related: ["singapore", "thailand", "bali"],
  }),
  make({
    slug: "bhutan",
    name: "Bhutan",
    country: "Bhutan",
    region: "international",
    prime: true,
    ribbon: "Most Popular Group Tours",
    tagline: "The last Himalayan kingdom of Gross National Happiness",
    hero: IMG.bhu4,
    gallery: [IMG.bhu1, IMG.bhu3, IMG.bhu2, IMG.him1],
    overview:
      "Bhutan is a rare, carefully protected Himalayan kingdom of fortress monasteries, prayer-flag ridges and immaculate valleys. It suits travellers seeking serenity, culture and clean mountain air — with the Tiger's Nest climb as its unforgettable centrepiece.",
    whyVisit: [
      "Pristine Himalayan landscapes and low tourist density",
      "Deep living Buddhist culture and dzong architecture",
      "Excellent for senior groups with gentle, well-paced routes",
      "Easy access via Paro flights or the Phuentsholing land route",
    ],
    bestTime: "March – May & September – November",
    bestTimeNote:
      "Spring brings rhododendron blooms while autumn offers crisp Himalayan views and major festivals.",
    idealFor: ["Family", "Couples", "Honeymoon", "Senior Citizens", "Friends"],
    attractions: [
      { name: "Paro Taktsang (Tiger's Nest)", desc: "Cliff-clinging monastery reached by a scenic ascent." },
      { name: "Punakha Dzong", desc: "Bhutan's most beautiful fortress at the river confluence." },
      { name: "Dochula Pass", desc: "108 chortens with a panorama of the eastern Himalaya." },
      { name: "Thimphu & Buddha Dordenma", desc: "Capital sights and the towering golden Buddha." },
    ],
    experiences: [
      "Traditional hot-stone bath and Bhutanese farmhouse dinner",
      "Archery experience with local villagers",
      "Tshechu festival viewing (seasonal)",
      "Gentle valley walks in Punakha and Phobjikha",
      "Handicraft and textile museum visits",
    ],
    visa: "Indian passport holders require a permit; a valid passport or Voter ID plus the Sustainable Development Fee applies.",
    hotels: [
      "Luxury Himalayan lodges in Paro & Punakha",
      "Boutique heritage hotels in Thimphu",
      "Comfortable valley resorts for group travel",
    ],
    related: ["nepal", "sikkim", "ladakh"],
  }),
  make({
    slug: "nepal",
    name: "Nepal",
    country: "Nepal",
    region: "international",
    prime: true,
    ribbon: "Most Popular Group Tours",
    tagline: "Himalayan dawns and timeless temple cities",
    hero: IMG.him1,
    gallery: [IMG.np1, IMG.bhu2, IMG.him6, IMG.him5],
    overview:
      "Nepal offers Everest sunrise flights, the lakeside calm of Pokhara, the temple squares of Kathmandu and the jungle safaris of Chitwan — all within a short, visa-free journey for Indian travellers. It is a superb choice for pilgrimage groups, families and first-time mountain travellers.",
    whyVisit: [
      "No visa required for Indian passport holders",
      "Everest mountain flights and Annapurna panoramas",
      "Pashupatinath and Muktinath pilgrimage circuits",
      "Wildlife safaris in Chitwan National Park",
    ],
    bestTime: "October – April",
    bestTimeNote: "October to April brings clear Himalayan visibility and comfortable daytime temperatures.",
    idealFor: ["Family", "Couples", "Senior Citizens", "Friends", "Corporate"],
    attractions: [
      { name: "Pashupatinath Temple", desc: "One of the most revered Shiva temples in the world." },
      { name: "Pokhara & Phewa Lake", desc: "Boating beneath the Annapurna and Machhapuchhre peaks." },
      { name: "Everest Mountain Flight", desc: "One-hour scenic flight along the highest peaks on earth." },
      { name: "Chitwan National Park", desc: "Jeep safari for rhino, gaur and Bengal tiger." },
    ],
    experiences: [
      "Sarangkot sunrise viewpoint",
      "Boudhanath and Swayambhunath heritage walk",
      "Muktinath pilgrimage by road or helicopter",
      "Paragliding over Pokhara valley",
      "Cultural dinner with Newari cuisine",
    ],
    visa: "No visa is required for Indian passport holders; valid photo identification is mandatory.",
    hotels: [
      "Lakeside resorts in Pokhara",
      "Heritage and five-star hotels in Kathmandu",
      "Jungle lodges near Chitwan",
    ],
    related: ["bhutan", "ladakh", "sikkim"],
  }),
  make({
    slug: "sri-lanka",
    name: "Sri Lanka",
    country: "Sri Lanka",
    region: "international",
    prime: true,
    ribbon: "Most Popular Group Tours",
    tagline: "The pearl of the Indian Ocean",
    hero: IMG.wl3,
    gallery: [IMG.ker4, IMG.th4, IMG.res4, IMG.wl1],
    overview:
      "Compact and astonishingly varied, Sri Lanka delivers tea-country train rides, leopard safaris in Yala, the sacred city of Kandy and golden southern beaches — often within a single week. Short flights and warm hospitality make it a favourite for families and Ramayana pilgrimage groups.",
    whyVisit: [
      "Short flight from India with easy entry formalities",
      "Beaches, hill country and wildlife in one loop",
      "Ramayana trail and Buddhist heritage circuits",
      "Excellent value five-star resorts",
    ],
    bestTime: "December – April",
    bestTimeNote:
      "December to April suits the south and west coasts; May to September is better for the east coast.",
    idealFor: ["Family", "Couples", "Honeymoon", "Senior Citizens", "Friends"],
    attractions: [
      { name: "Temple of the Sacred Tooth, Kandy", desc: "Sri Lanka's most venerated Buddhist shrine." },
      { name: "Nuwara Eliya & Tea Country", desc: "Colonial hill station, estates and the Ella scenic train." },
      { name: "Yala National Park", desc: "One of the world's highest leopard densities." },
      { name: "Sigiriya Rock Fortress", desc: "UNESCO citadel rising from the central plains." },
    ],
    experiences: [
      "Kandy to Ella observation-car train journey",
      "Whale watching from Mirissa (seasonal)",
      "Ramayana trail with Ashok Vatika and Sita Amman temple",
      "Galle Fort heritage evening",
      "Ayurvedic wellness retreat on the south coast",
    ],
    visa: "An electronic travel authorisation (ETA) is required for Indian passport holders.",
    hotels: [
      "Beach resorts in Bentota and Galle",
      "Tea-estate bungalows in Nuwara Eliya",
      "Safari lodges near Yala and Udawalawe",
    ],
    related: ["maldives", "kerala", "thailand"],
  }),

  /* ────────────────  OTHER INTERNATIONAL  ──────────────── */
  make({
    slug: "azerbaijan",
    name: "Azerbaijan",
    country: "Azerbaijan",
    region: "international",
    tagline: "Land of fire, Caucasus peaks and Caspian breezes",
    hero: IMG.him5,
    gallery: [IMG.sg6, IMG.res5, IMG.him4, IMG.tur3],
    overview:
      "Baku's flame towers and UNESCO old city sit beside the alpine villages of Gabala and Sheki, making Azerbaijan a fresh, affordable and photogenic escape with an easy e-visa process.",
    whyVisit: [
      "Simple e-visa and short flying time",
      "Cool mountain resorts through the Indian summer",
      "Excellent Indian dining options in Baku",
      "Great value luxury hotels",
    ],
    bestTime: "April – June & September – November",
    bestTimeNote: "Spring and autumn deliver mild weather across Baku and the Caucasus foothills.",
    idealFor: ["Family", "Couples", "Honeymoon", "Friends", "Corporate"],
    attractions: [
      { name: "Icherisheher (Old City)", desc: "Walled UNESCO quarter with the Maiden Tower." },
      { name: "Flame Towers & Highland Park", desc: "Baku's illuminated skyline and Caspian views." },
      { name: "Gabala", desc: "Cable cars, waterfalls and alpine resorts." },
      { name: "Gobustan & Mud Volcanoes", desc: "Ancient petroglyphs and bubbling lunar terrain." },
    ],
    experiences: [
      "Caspian promenade evening walk",
      "Sheki khan palace and silk road caravanserai",
      "Off-road jeep tour to Laza waterfalls",
      "Tufandag cable car experience",
    ],
    visa: "An ASAN e-visa is available for Indian passport holders.",
    hotels: ["Five-star Caspian-view hotels in Baku", "Mountain resorts in Gabala", "Boutique stays in Old City"],
    related: ["georgia", "turkey", "kazakhstan"],
  }),
  make({
    slug: "maldives",
    name: "Maldives",
    country: "Maldives",
    region: "international",
    tagline: "Overwater villas and impossible blues",
    hero: IMG.mld1,
    gallery: [IMG.mld2, IMG.res6, IMG.th4, IMG.bali5],
    overview:
      "The Maldives is barefoot luxury distilled: a private island, a lagoon that glows turquoise and nothing on the schedule. It remains the world's most requested honeymoon and anniversary destination — and increasingly a family favourite thanks to superb kids' clubs.",
    whyVisit: [
      "Overwater and beach villas with private pools",
      "World-class snorkelling and diving reefs",
      "Complete privacy for honeymoons and anniversaries",
      "Short flight with seaplane or speedboat transfers",
    ],
    bestTime: "November – April",
    bestTimeNote: "November to April is the dry season with calm seas and excellent underwater visibility.",
    idealFor: ["Couples", "Honeymoon", "Family", "Friends"],
    attractions: [
      { name: "House Reef Snorkelling", desc: "Turtles, rays and coral gardens steps from your villa." },
      { name: "Sandbank Picnic", desc: "A private strip of sand set just for two." },
      { name: "Male & Maafushi", desc: "Local island culture and craft markets." },
      { name: "Bioluminescent Beaches", desc: "Seasonal 'sea of stars' glow after dark." },
    ],
    experiences: [
      "Seaplane transfer with aerial atoll views",
      "Sunset dolphin cruise",
      "Underwater or beach candlelight dinner",
      "Couples' spa over the lagoon",
    ],
    visa: "A free visa on arrival is granted to Indian passport holders with confirmed resort bookings.",
    hotels: ["Overwater villa resorts", "Private-pool beach villas", "Family resorts with kids' clubs"],
    related: ["mauritius", "seychelles", "bali"],
  }),
  make({
    slug: "mauritius",
    name: "Mauritius",
    country: "Mauritius",
    region: "international",
    tagline: "Volcanic peaks meeting lagoon calm",
    hero: IMG.res3,
    gallery: [IMG.bali1, IMG.res6, IMG.th1, IMG.res5],
    overview:
      "Mauritius pairs lagoon-side resorts with waterfalls, botanical gardens and a warm Indian-origin culture that makes Indian travellers feel instantly at home — ideal for honeymoons and multi-generational family holidays.",
    whyVisit: [
      "Calm, swimmable lagoons perfect for families",
      "Indian cuisine and culture widely available",
      "All-inclusive luxury resort options",
      "Catamaran cruises and dolphin encounters",
    ],
    bestTime: "May – December",
    bestTimeNote: "May to December brings dry, comfortable weather across the island.",
    idealFor: ["Couples", "Honeymoon", "Family", "Senior Citizens", "Friends"],
    attractions: [
      { name: "Chamarel Seven Coloured Earth", desc: "Surreal dunes and a dramatic waterfall." },
      { name: "Ile aux Cerfs", desc: "Catamaran day trip to a postcard island." },
      { name: "Port Louis & Caudan", desc: "Capital markets, cafés and waterfront shopping." },
      { name: "Grand Bassin", desc: "Sacred crater lake with towering Shiva statue." },
    ],
    experiences: [
      "Catamaran cruise with barbecue lunch",
      "Underwater sea walk at Belle Mare",
      "Black River Gorges nature drive",
      "Sunset dolphin cruise at Tamarin Bay",
    ],
    visa: "Indian passport holders receive a free visa on arrival for tourism.",
    hotels: ["All-inclusive lagoon resorts", "Honeymoon suites in Belle Mare", "Family resorts in Flic en Flac"],
    related: ["maldives", "seychelles", "kenya"],
  }),
  make({
    slug: "turkey",
    name: "Turkey",
    country: "Türkiye",
    region: "international",
    tagline: "Where continents, empires and balloons meet",
    hero: IMG.tur4,
    gallery: [IMG.tur2, IMG.tur3, IMG.tur5, IMG.sg2],
    overview:
      "Turkey delivers Istanbul's imperial skyline, Cappadocia's balloon-filled dawn, Pamukkale's white terraces and the turquoise Aegean coast — one of the most visually rewarding itineraries we design.",
    whyVisit: [
      "Cappadocia hot air balloon sunrise",
      "Byzantine and Ottoman heritage in Istanbul",
      "Cave hotels and gulet cruises",
      "Superb shopping and cuisine",
    ],
    bestTime: "April – June & September – November",
    bestTimeNote: "Spring and autumn offer mild weather and the best balloon flight conditions.",
    idealFor: ["Family", "Couples", "Honeymoon", "Friends", "Corporate"],
    attractions: [
      { name: "Hagia Sophia & Blue Mosque", desc: "Istanbul's twin architectural masterpieces." },
      { name: "Cappadocia", desc: "Fairy chimneys, cave hotels and sunrise balloons." },
      { name: "Pamukkale", desc: "Cotton-castle travertine terraces and Hierapolis." },
      { name: "Bosphorus Strait", desc: "Cruise between Europe and Asia past Ottoman palaces." },
    ],
    experiences: [
      "Hot air balloon flight over Göreme",
      "Bosphorus dinner cruise with live music",
      "Turkish hammam ritual",
      "Grand Bazaar and Spice Market shopping walk",
    ],
    visa: "Indian passport holders require a Turkish visa; e-visa eligibility depends on holding a valid third-country visa.",
    hotels: ["Cave hotels in Cappadocia", "Bosphorus-view hotels in Istanbul", "Aegean coast resorts"],
    related: ["georgia", "egypt", "azerbaijan"],
  }),
  make({
    slug: "georgia",
    name: "Georgia",
    country: "Georgia",
    region: "international",
    tagline: "Caucasus mountains, wine valleys and cobbled charm",
    hero: IMG.him6,
    gallery: [IMG.him4, IMG.him1, IMG.res4, IMG.him5],
    overview:
      "Georgia is Europe at Asian value — Tbilisi's sulphur baths and old town, the ski slopes of Gudauri, Kazbegi's mountain chapel and Kakheti's ancient wine estates.",
    whyVisit: [
      "Snow experiences without a long-haul flight",
      "Affordable luxury and warm hospitality",
      "Dramatic mountain drives and monasteries",
      "Growing Indian dining scene in Tbilisi",
    ],
    bestTime: "April – June & September – October",
    bestTimeNote: "Spring and autumn are ideal; December to March suits snow and ski travel.",
    idealFor: ["Family", "Couples", "Honeymoon", "Friends", "Corporate"],
    attractions: [
      { name: "Gergeti Trinity Church", desc: "Hilltop chapel beneath Mount Kazbek." },
      { name: "Old Tbilisi", desc: "Sulphur baths, cable car and Narikala Fortress." },
      { name: "Gudauri", desc: "Cable cars, snow sports and alpine panoramas." },
      { name: "Kakheti Wine Region", desc: "8,000 years of winemaking heritage." },
    ],
    experiences: [
      "Jeep excursion to Kazbegi",
      "Wine tasting in a traditional qvevri cellar",
      "Paragliding over Gudauri",
      "Georgian supra feast with folk music",
    ],
    visa: "Indian passport holders require a Georgian visa or an approved e-visa.",
    hotels: ["Boutique hotels in Old Tbilisi", "Ski-in resorts in Gudauri", "Guesthouse estates in Kakheti"],
    related: ["azerbaijan", "turkey", "kazakhstan"],
  }),
  make({
    slug: "kazakhstan",
    name: "Kazakhstan",
    country: "Kazakhstan",
    region: "international",
    tagline: "Alpine lakes, steppe skies and modern skylines",
    hero: IMG.him2,
    gallery: [IMG.him3, IMG.him4, IMG.him1, IMG.sg2],
    overview:
      "Almaty's alpine backdrop, the turquoise Kolsai and Kaindy lakes and the futuristic capital Astana make Kazakhstan an emerging favourite — especially for snow-seeking families and friends' groups.",
    whyVisit: [
      "Visa-free entry for Indian passport holders (short stays)",
      "Guaranteed snow experiences at Shymbulak",
      "Spectacular lakes and canyon landscapes",
      "Short flights and low crowds",
    ],
    bestTime: "May – September & December – February",
    bestTimeNote: "Summer suits lakes and hiking; winter delivers reliable snow at Shymbulak and Medeu.",
    idealFor: ["Family", "Couples", "Friends", "Corporate"],
    attractions: [
      { name: "Shymbulak & Medeu", desc: "Cable cars, skiing and the world's highest skating rink." },
      { name: "Big Almaty Lake", desc: "Alpine turquoise lake framed by pine ridges." },
      { name: "Charyn Canyon", desc: "The 'Valley of Castles' carved in red rock." },
      { name: "Kolsai & Kaindy Lakes", desc: "Submerged forest and mirror-still mountain water." },
    ],
    experiences: [
      "Cable car ascent to Shymbulak peak",
      "Kok Tobe hill and Almaty city tour",
      "Steppe nomad yurt experience",
      "Astana modern architecture tour",
    ],
    visa: "Indian passport holders currently enjoy visa-free entry for short tourist stays, subject to change.",
    hotels: ["City hotels in Almaty", "Mountain resorts near Shymbulak", "Contemporary hotels in Astana"],
    related: ["georgia", "azerbaijan", "turkey"],
  }),
  make({
    slug: "egypt",
    name: "Egypt",
    country: "Egypt",
    region: "international",
    tagline: "Pyramids, Nile cruises and 5,000 years of wonder",
    hero: IMG.egy1,
    gallery: [IMG.tur1, IMG.tur5, IMG.res5, IMG.th4],
    overview:
      "From the Giza pyramids to a Nile cruise between Luxor and Aswan and the reef resorts of the Red Sea, Egypt is history at monumental scale — a bucket-list journey we design with expert Egyptologists.",
    whyVisit: [
      "The last surviving Ancient Wonder of the World",
      "Luxury Nile cruises with private guiding",
      "Red Sea diving and beach resorts",
      "Fascinating for teenagers and history lovers",
    ],
    bestTime: "October – April",
    bestTimeNote: "October to April keeps sightseeing comfortable across Cairo, Luxor and Aswan.",
    idealFor: ["Family", "Couples", "Senior Citizens", "Friends", "Corporate"],
    attractions: [
      { name: "Pyramids of Giza & Sphinx", desc: "The Great Pyramid and its guardian on the desert plateau." },
      { name: "Valley of the Kings", desc: "Royal tombs painted in extraordinary colour." },
      { name: "Nile Cruise Luxor–Aswan", desc: "Temples of Karnak, Edfu, Kom Ombo and Philae." },
      { name: "Grand Egyptian Museum", desc: "The world's largest archaeological museum." },
    ],
    experiences: [
      "Hot air balloon over Luxor's West Bank",
      "Felucca sail at sunset in Aswan",
      "Sound and light show at the pyramids",
      "Red Sea snorkelling in Hurghada",
    ],
    visa: "Indian passport holders require an Egyptian visa; e-visa options may apply.",
    hotels: ["Pyramid-view hotels in Giza", "Five-star Nile cruise ships", "Red Sea beach resorts"],
    related: ["turkey", "kenya", "dubai"],
  }),
  make({
    slug: "hong-kong",
    name: "Hong Kong",
    country: "Hong Kong SAR",
    region: "international",
    tagline: "Neon harbour nights and Disney days",
    hero: IMG.sg6,
    gallery: [IMG.sg2, IMG.sg5, IMG.sg1, IMG.sg4],
    overview:
      "Hong Kong is a thrilling compression of skyline, harbour, hillside temples and world-class theme parks — with Macau's Portuguese heritage just an hour away by ferry.",
    whyVisit: [
      "Disneyland and Ocean Park for families",
      "Victoria Peak and Symphony of Lights",
      "Superb shopping and dining",
      "Easy pairing with Macau",
    ],
    bestTime: "October – March",
    bestTimeNote: "October to March brings cool, dry and clear conditions across the territory.",
    idealFor: ["Family", "Couples", "Friends", "Corporate"],
    attractions: [
      { name: "Victoria Peak", desc: "Peak Tram ascent to the classic harbour panorama." },
      { name: "Hong Kong Disneyland", desc: "A full day of family magic." },
      { name: "Big Buddha, Lantau", desc: "Ngong Ping cable car to the Tian Tan Buddha." },
      { name: "Macau", desc: "Ruins of St. Paul's, Venetian and Cotai Strip." },
    ],
    experiences: [
      "Star Ferry crossing at dusk",
      "Symphony of Lights harbour cruise",
      "Temple Street night market",
      "Dim sum tasting trail",
    ],
    visa: "Indian passport holders may require pre-arrival registration or a visa depending on current policy.",
    hotels: ["Harbour-view hotels in Tsim Sha Tsui", "Disney-themed resorts on Lantau", "Luxury towers in Central"],
    related: ["singapore", "thailand", "philippines"],
  }),
  make({
    slug: "philippines",
    name: "Philippines",
    country: "Philippines",
    region: "international",
    tagline: "7,000 islands of impossible water",
    hero: IMG.bali5,
    gallery: [IMG.th1, IMG.th2, IMG.res6, IMG.mld2],
    overview:
      "Palawan's lagoons, Boracay's white sand and Cebu's dive sites make the Philippines one of Asia's most beautiful and least crowded island escapes.",
    whyVisit: [
      "El Nido and Coron island-hopping",
      "Some of the world's best beaches",
      "Warm, English-speaking hospitality",
      "Excellent diving and snorkelling",
    ],
    bestTime: "November – May",
    bestTimeNote: "November to May is the dry season with calm seas for island-hopping.",
    idealFor: ["Couples", "Honeymoon", "Friends", "Family"],
    attractions: [
      { name: "El Nido, Palawan", desc: "Hidden lagoons framed by limestone cliffs." },
      { name: "Boracay White Beach", desc: "Four kilometres of powder-soft sand." },
      { name: "Coron Bay", desc: "Wreck diving and Kayangan Lake." },
      { name: "Chocolate Hills, Bohol", desc: "Rolling geological curiosities and tarsier sanctuary." },
    ],
    experiences: [
      "Private banca island-hopping tour",
      "Underground River in Puerto Princesa",
      "Sunset sailing on a paraw",
      "Island beach dinner setup",
    ],
    visa: "Indian passport holders may qualify for visa-free entry when holding valid AJACSSUK visas; otherwise a visa is required.",
    hotels: ["Beachfront resorts in El Nido", "Boracay Station 1 luxury hotels", "Dive resorts in Cebu"],
    related: ["bali", "thailand", "maldives"],
  }),
  make({
    slug: "kenya",
    name: "Kenya",
    country: "Kenya",
    region: "international",
    tagline: "The original safari, under acacia skies",
    hero: IMG.wl1,
    gallery: [IMG.wl3, IMG.wl5, IMG.wl2, IMG.res4],
    overview:
      "Kenya is the classic African safari: the Masai Mara's big cats, Amboseli's elephants beneath Kilimanjaro and the white beaches of Diani for a coastal finish.",
    whyVisit: [
      "The Great Migration in the Masai Mara (seasonal)",
      "Big Five game viewing with expert rangers",
      "Balloon safaris and Maasai cultural visits",
      "Safari plus beach combination itineraries",
    ],
    bestTime: "July – October & January – March",
    bestTimeNote:
      "July to October coincides with the Great Migration; January to March offers excellent general game viewing.",
    idealFor: ["Family", "Couples", "Honeymoon", "Friends", "Corporate"],
    attractions: [
      { name: "Masai Mara National Reserve", desc: "Iconic plains and the river crossings." },
      { name: "Amboseli National Park", desc: "Elephant herds framed by Mount Kilimanjaro." },
      { name: "Lake Nakuru", desc: "Flamingos, rhino and acacia forests." },
      { name: "Diani Beach", desc: "Indian Ocean white sand for a restful finale." },
    ],
    experiences: [
      "Sunrise hot air balloon over the Mara",
      "Private game drives with a dedicated ranger",
      "Maasai village cultural visit",
      "Bush breakfast and sundowner setup",
    ],
    visa: "Indian passport holders require an electronic travel authorisation for Kenya.",
    hotels: ["Luxury tented camps in the Mara", "Lodges in Amboseli", "Beach resorts in Diani"],
    related: ["mauritius", "seychelles", "egypt"],
  }),
  make({
    slug: "seychelles",
    name: "Seychelles",
    country: "Seychelles",
    region: "international",
    tagline: "Granite boulders, jade water, absolute privacy",
    hero: IMG.res6,
    gallery: [IMG.bali3, IMG.mld2, IMG.th4, IMG.bali5],
    overview:
      "Seychelles is the connoisseur's Indian Ocean escape — Mahé, Praslin and La Digue offer sculpted granite beaches, rare wildlife and blissfully uncrowded luxury.",
    whyVisit: [
      "Visa-free entry for Indian passport holders",
      "Anse Source d'Argent, among the world's most photographed beaches",
      "Vallée de Mai UNESCO palm forest",
      "Ultra-private island resorts",
    ],
    bestTime: "April – May & October – November",
    bestTimeNote: "The inter-monsoon months bring calm seas, clear skies and ideal diving visibility.",
    idealFor: ["Couples", "Honeymoon", "Family", "Friends"],
    attractions: [
      { name: "Anse Source d'Argent, La Digue", desc: "Granite sculptures over shallow turquoise water." },
      { name: "Vallée de Mai, Praslin", desc: "Home of the legendary coco de mer palm." },
      { name: "Beau Vallon, Mahé", desc: "Sunset swimming and seafood grills." },
      { name: "Curieuse Island", desc: "Giant Aldabra tortoises roaming free." },
    ],
    experiences: [
      "Island-hopping by catamaran",
      "Bicycle exploration of La Digue",
      "Creole cooking experience",
      "Private beach dinner under the stars",
    ],
    visa: "No visa is required for Indian passport holders; a visitor's permit is issued on arrival.",
    hotels: ["Private island resorts", "Hillside villas on Mahé", "Beachfront boutique hotels on Praslin"],
    related: ["maldives", "mauritius", "kenya"],
  }),

  /* ────────────────  DOMESTIC  ──────────────── */
  make({
    slug: "rajasthan",
    name: "Rajasthan",
    country: "India",
    region: "domestic",
    tagline: "Our home. Our heritage. Our finest storytelling.",
    hero: IMG.raj3,
    gallery: [IMG.raj1, IMG.raj4, IMG.raj6, IMG.raj2],
    overview:
      "Rajasthan is where our company began — in Jodhpur, beneath Mehrangarh, where our office still stands today. Palace hotels, lake sunsets in Udaipur, the golden fort of Jaisalmer and the pink streets of Jaipur: nobody designs Rajasthan the way we do, because it is home.",
    whyVisit: [
      "Live like royalty in authentic palace hotels",
      "Desert camps, camel safaris and folk performances",
      "Extraordinary crafts, textiles and cuisine",
      "Our deepest local network — we are based in Jodhpur",
    ],
    bestTime: "October – March",
    bestTimeNote: "October to March brings cool, clear days perfect for forts, deserts and festivals.",
    idealFor: ["Family", "Couples", "Honeymoon", "Senior Citizens", "Friends", "Corporate"],
    attractions: [
      { name: "Amber Fort & Hawa Mahal, Jaipur", desc: "The Pink City's most photographed icons." },
      { name: "Lake Pichola, Udaipur", desc: "Sunset boat ride past the City Palace and island palaces." },
      { name: "Jaisalmer Golden Fort", desc: "A living fort city of honey sandstone." },
      { name: "Mehrangarh Fort, Jodhpur", desc: "Towering above the blue city." },
    ],
    experiences: [
      "Heritage palace stay with royal dining",
      "Sam sand dunes desert camp with folk music",
      "Vintage car and hot air balloon over Jaipur",
      "Destination wedding and corporate offsite planning",
      "Ranthambore tiger safari extension",
    ],
    hotels: ["Royal palace hotels", "Luxury desert camps", "Boutique heritage havelis"],
    related: ["golden-triangle", "gujarat", "madhya-pradesh"],
  }),
  make({
    slug: "kashmir",
    name: "Kashmir",
    country: "India",
    region: "domestic",
    tagline: "Paradise, precisely as promised",
    hero: IMG.him1,
    gallery: [IMG.him6, IMG.him4, IMG.np1, IMG.him5],
    overview:
      "Dal Lake shikaras, Gulmarg's gondola, Pahalgam's meadows and Sonmarg's glaciers — Kashmir is India's most romantic valley and a firm favourite for honeymooners and families alike.",
    whyVisit: [
      "Houseboat stays on Dal Lake",
      "Gulmarg Gondola, one of the world's highest cable cars",
      "Tulip Garden in spring and snow in winter",
      "Warm hospitality and legendary Wazwan cuisine",
    ],
    bestTime: "March – October (snow: December – February)",
    bestTimeNote:
      "March to October is green and mild; December to February delivers the classic Kashmiri snow experience.",
    idealFor: ["Family", "Couples", "Honeymoon", "Senior Citizens", "Friends"],
    attractions: [
      { name: "Dal Lake & Shikara Ride", desc: "Floating gardens, markets and houseboats." },
      { name: "Gulmarg Gondola", desc: "Two-phase cable car to Apharwat Peak." },
      { name: "Pahalgam & Betaab Valley", desc: "Pine meadows along the Lidder river." },
      { name: "Mughal Gardens", desc: "Shalimar, Nishat and Chashme Shahi terraces." },
    ],
    experiences: [
      "Deluxe houseboat night on Dal Lake",
      "Snow activities at Gulmarg",
      "Aru and Chandanwari day excursion",
      "Kashmiri Wazwan dining experience",
    ],
    hotels: ["Premium houseboats on Dal Lake", "Luxury resorts in Gulmarg", "Riverside hotels in Pahalgam"],
    related: ["ladakh", "himachal-pradesh", "uttarakhand"],
  }),
  make({
    slug: "ladakh",
    name: "Ladakh",
    country: "India",
    region: "domestic",
    tagline: "High-altitude silence and cinematic blue",
    hero: IMG.him3,
    gallery: [IMG.him2, IMG.him5, IMG.him4, IMG.him6],
    overview:
      "Ladakh is the roof of India — Pangong's changing blues, Nubra's sand dunes, Khardung La's thin bright air and monasteries perched above the Indus. A journey for the adventurous heart, planned with careful acclimatisation.",
    whyVisit: [
      "Pangong Tso and Tso Moriri lakes",
      "Nubra Valley dunes and double-humped camels",
      "Ancient monasteries at Thiksey and Hemis",
      "Legendary road trips and biking routes",
    ],
    bestTime: "May – September",
    bestTimeNote: "May to September has open passes, accessible lakes and stable mountain weather.",
    idealFor: ["Couples", "Friends", "Family", "Corporate"],
    attractions: [
      { name: "Pangong Tso", desc: "The lake that changes colour through the day." },
      { name: "Nubra Valley", desc: "Diskit monastery, dunes and camel rides." },
      { name: "Khardung La", desc: "One of the world's highest motorable passes." },
      { name: "Thiksey Monastery", desc: "Sunrise prayers in a hilltop gompa." },
    ],
    experiences: [
      "Luxury camp night beside Pangong",
      "Magnetic Hill and Sangam confluence drive",
      "Monastery morning prayer ceremony",
      "Guided motorbike expedition",
    ],
    hotels: ["Boutique hotels in Leh", "Luxury camps in Nubra & Pangong", "Heritage Ladakhi homestays"],
    related: ["kashmir", "himachal-pradesh", "sikkim"],
  }),
  make({
    slug: "kerala",
    name: "Kerala",
    country: "India",
    region: "domestic",
    tagline: "God's own country, at its own pace",
    hero: IMG.ker2,
    gallery: [IMG.ker1, IMG.ker5, IMG.ker3, IMG.ker6],
    overview:
      "Kerala moves gently: a private houseboat through the Alleppey backwaters, tea-scented mornings in Munnar, Ayurvedic therapy in Kumarakom and beach evenings in Kovalam. Perfect for honeymooners and senior travellers.",
    whyVisit: [
      "Private houseboat cruising with onboard chef",
      "Authentic Ayurveda and wellness retreats",
      "Tea and spice plantations in Munnar & Thekkady",
      "Gentle pace ideal for senior citizens",
    ],
    bestTime: "September – March",
    bestTimeNote: "September to March is pleasant and dry; monsoon months are prized for Ayurvedic treatment.",
    idealFor: ["Couples", "Honeymoon", "Family", "Senior Citizens", "Friends"],
    attractions: [
      { name: "Alleppey Backwaters", desc: "Overnight premium houseboat through the canals." },
      { name: "Munnar Tea Country", desc: "Rolling estates, Eravikulam and Mattupetty." },
      { name: "Thekkady & Periyar", desc: "Spice plantations and lake wildlife cruise." },
      { name: "Fort Kochi", desc: "Chinese fishing nets, Jew Town and colonial streets." },
    ],
    experiences: [
      "Private houseboat with candlelight dinner",
      "Kathakali and Kalaripayattu performance",
      "Ayurvedic rejuvenation programme",
      "Sunset at Kovalam or Varkala cliffs",
    ],
    hotels: ["Luxury houseboats", "Tea-estate resorts in Munnar", "Ayurvedic beach resorts in Kovalam"],
    related: ["tamil-nadu", "karnataka", "goa"],
  }),
  make({
    slug: "goa",
    name: "Goa",
    country: "India",
    region: "domestic",
    tagline: "Sunset, susegad and Portuguese soul",
    hero: IMG.bali3,
    gallery: [IMG.th4, IMG.res5, IMG.bali4, IMG.res3],
    overview:
      "Goa is India's easiest luxury beach break — north for energy and beach clubs, south for serene five-star sands, with Latin quarters, river cruises and spice plantations in between.",
    whyVisit: [
      "Five-star beach resorts on quiet southern sands",
      "Heritage Latin quarters and churches",
      "Water sports, cruises and dolphin trips",
      "Superb dining, from beach shacks to fine dining",
    ],
    bestTime: "November – February",
    bestTimeNote: "November to February brings cool breezes, calm seas and the festive season.",
    idealFor: ["Couples", "Honeymoon", "Family", "Friends", "Corporate"],
    attractions: [
      { name: "Palolem & Agonda", desc: "Crescent bays in serene South Goa." },
      { name: "Old Goa Churches", desc: "Basilica of Bom Jesus and Se Cathedral." },
      { name: "Fort Aguada & Chapora", desc: "Sunset forts over the Arabian Sea." },
      { name: "Dudhsagar Falls", desc: "Jeep safari to the four-tiered cascade." },
    ],
    experiences: [
      "Private yacht sunset cruise on the Mandovi",
      "Beachfront villa with chef service",
      "Spice plantation lunch experience",
      "Corporate offsites and beach gala dinners",
    ],
    hotels: ["Luxury beach resorts in South Goa", "Boutique Portuguese villas", "Riverside spa resorts"],
    related: ["kerala", "andaman", "karnataka"],
  }),
  make({
    slug: "andaman",
    name: "Andaman Islands",
    country: "India",
    region: "domestic",
    tagline: "India's own turquoise archipelago",
    hero: IMG.th1,
    gallery: [IMG.bali5, IMG.mld2, IMG.res6, IMG.th2],
    overview:
      "Radhanagar Beach at sunset, coral reefs at Elephant Beach, glass-bottom boats at North Bay and the moving history of Cellular Jail — the Andamans deliver an international-standard beach holiday within India.",
    whyVisit: [
      "Asia's finest beaches without an international flight",
      "Scuba diving and snorkelling for beginners",
      "Sea plane and private ferry transfers",
      "Wonderful for honeymoons and families",
    ],
    bestTime: "October – May",
    bestTimeNote: "October to May offers calm seas, clear visibility and reliable ferry schedules.",
    idealFor: ["Couples", "Honeymoon", "Family", "Friends"],
    attractions: [
      { name: "Radhanagar Beach, Havelock", desc: "Consistently ranked among Asia's best beaches." },
      { name: "Elephant Beach", desc: "Snorkelling, sea walking and water sports." },
      { name: "Cellular Jail", desc: "National memorial and evening light & sound show." },
      { name: "Neil Island", desc: "Natural coral bridge and tranquil bays." },
    ],
    experiences: [
      "Introductory scuba dive with certified instructors",
      "Private beach candlelight dinner",
      "Glass-bottom boat over coral gardens",
      "Kayaking through mangrove creeks",
    ],
    hotels: ["Beach resorts on Havelock", "Sea-view hotels in Port Blair", "Eco-luxury cottages on Neil Island"],
    related: ["goa", "kerala", "maldives"],
  }),
  make({
    slug: "himachal-pradesh",
    name: "Himachal Pradesh",
    country: "India",
    region: "domestic",
    tagline: "Deodar forests, apple valleys and snow",
    hero: IMG.him6,
    gallery: [IMG.him1, IMG.him5, IMG.bhu2, IMG.him4],
    overview:
      "Shimla's colonial charm, Manali's snow, the Tibetan calm of Dharamshala and the drama of Spiti — Himachal is India's most versatile mountain state for families, couples and friends.",
    whyVisit: [
      "Reliable snow experiences at Solang and Rohtang",
      "Toy train to Shimla through 100 tunnels",
      "Adventure sports and river rafting",
      "Easy road access and comfortable resorts",
    ],
    bestTime: "March – June & September – December",
    bestTimeNote: "Spring and autumn are glorious; December to February is best for snow.",
    idealFor: ["Family", "Couples", "Honeymoon", "Senior Citizens", "Friends", "Corporate"],
    attractions: [
      { name: "Solang Valley", desc: "Snow sports, ropeway and paragliding." },
      { name: "Kalka–Shimla Toy Train", desc: "UNESCO heritage mountain railway." },
      { name: "McLeod Ganj", desc: "Tibetan monasteries and Himalayan cafés." },
      { name: "Atal Tunnel & Sissu", desc: "Gateway to the Lahaul valley." },
    ],
    experiences: [
      "Riverside luxury camp in Manali",
      "Paragliding at Bir Billing",
      "Apple orchard and heritage estate stay",
      "Team offsites in Shimla and Kasauli",
    ],
    hotels: ["Luxury mountain resorts in Manali", "Colonial heritage hotels in Shimla", "Boutique stays in Dharamshala"],
    related: ["uttarakhand", "kashmir", "ladakh"],
  }),
  make({
    slug: "uttarakhand",
    name: "Uttarakhand",
    country: "India",
    region: "domestic",
    tagline: "Devbhoomi — the land of the gods",
    hero: IMG.him5,
    gallery: [IMG.him1, IMG.him4, IMG.bhu2, IMG.him6],
    overview:
      "From Ganga aarti at Rishikesh to Nainital's lakes, Auli's snow slopes and the Char Dham pilgrimage, Uttarakhand serves spiritual travellers, families and adventure seekers with equal grace.",
    whyVisit: [
      "Char Dham and Haridwar–Rishikesh pilgrimage",
      "Jim Corbett tiger safaris",
      "Auli skiing and cable car",
      "Yoga and wellness retreats on the Ganges",
    ],
    bestTime: "March – June & September – November",
    bestTimeNote: "Spring and autumn are ideal; Char Dham yatra runs from April/May to October/November.",
    idealFor: ["Family", "Couples", "Senior Citizens", "Friends", "Corporate"],
    attractions: [
      { name: "Ganga Aarti, Rishikesh & Haridwar", desc: "The river ceremony at dusk." },
      { name: "Jim Corbett National Park", desc: "India's oldest national park." },
      { name: "Nainital & Mussoorie", desc: "Classic lake and hill station getaways." },
      { name: "Auli", desc: "Snow slopes with Nanda Devi views." },
    ],
    experiences: [
      "Char Dham yatra by road or helicopter",
      "Riverside luxury resort with yoga sessions",
      "Corbett jungle safari with naturalists",
      "White water rafting on the Ganges",
    ],
    hotels: ["Riverside resorts in Rishikesh", "Jungle lodges near Corbett", "Lake-view hotels in Nainital"],
    related: ["himachal-pradesh", "kashmir", "madhya-pradesh"],
  }),
  make({
    slug: "sikkim",
    name: "Sikkim",
    country: "India",
    region: "domestic",
    tagline: "Kanchenjunga mornings and monastery bells",
    hero: IMG.bhu2,
    gallery: [IMG.bhu1, IMG.him1, IMG.np1, IMG.bhu3],
    overview:
      "Sikkim delivers Himalayan grandeur with immaculate calm — Gangtok's ropeway, Tsomgo Lake, Nathula Pass and the sunrise over Kanchenjunga from Pelling and Darjeeling.",
    whyVisit: [
      "Third-highest peak on earth on the horizon",
      "Clean, safe and beautifully organised",
      "Monasteries at Rumtek and Pemayangtse",
      "Pairs perfectly with Darjeeling and Bhutan",
    ],
    bestTime: "March – May & October – December",
    bestTimeNote: "Spring blooms and autumn clarity are best; winter offers crisp snow at higher passes.",
    idealFor: ["Family", "Couples", "Honeymoon", "Senior Citizens", "Friends"],
    attractions: [
      { name: "Tsomgo Lake & Baba Mandir", desc: "Glacial lake at 12,400 feet." },
      { name: "Nathula Pass", desc: "Historic Indo-China border route (permit required)." },
      { name: "Rumtek Monastery", desc: "Seat of the Karma Kagyu lineage." },
      { name: "Pelling Skywalk", desc: "Glass walkway facing Kanchenjunga." },
    ],
    experiences: [
      "Kanchenjunga sunrise from Tiger Hill, Darjeeling",
      "Darjeeling Himalayan Railway toy train ride",
      "Tea estate tour and tasting",
      "Yumthang Valley of Flowers excursion",
    ],
    hotels: ["Mountain-view hotels in Gangtok", "Heritage tea bungalows in Darjeeling", "Boutique resorts in Pelling"],
    related: ["north-east-india", "bhutan", "nepal"],
  }),
  make({
    slug: "north-east-india",
    name: "North East India",
    country: "India",
    region: "domestic",
    tagline: "Seven sisters, endless discovery",
    hero: IMG.vn3,
    gallery: [IMG.vn1, IMG.him1, IMG.bhu2, IMG.vn5],
    overview:
      "Meghalaya's living root bridges, Assam's Kaziranga rhinos, Arunachal's Tawang monastery and Nagaland's Hornbill Festival — the North East is India's most rewarding frontier for curious travellers.",
    whyVisit: [
      "Cleanest village in Asia — Mawlynnong",
      "Kaziranga one-horned rhino safaris",
      "Living root bridges and crystal-clear Umngot river",
      "Vibrant tribal festivals and cuisine",
    ],
    bestTime: "October – April",
    bestTimeNote: "October to April is dry and clear; the Hornbill Festival takes place each December.",
    idealFor: ["Family", "Couples", "Friends", "Corporate"],
    attractions: [
      { name: "Cherrapunji & Living Root Bridges", desc: "Double-decker bridges grown from rubber fig roots." },
      { name: "Dawki & Umngot River", desc: "Boating over glass-clear water." },
      { name: "Kaziranga National Park", desc: "UNESCO home of the one-horned rhinoceros." },
      { name: "Tawang Monastery", desc: "India's largest monastery at 10,000 feet." },
    ],
    experiences: [
      "Elephant and jeep safari in Kaziranga",
      "Brahmaputra river cruise",
      "Tribal village homestay experience",
      "Hornbill Festival viewing (December)",
    ],
    hotels: ["Resorts in Shillong", "Wildlife lodges at Kaziranga", "Boutique stays in Guwahati"],
    related: ["sikkim", "bhutan", "odisha"],
  }),
  make({
    slug: "gujarat",
    name: "Gujarat",
    country: "India",
    region: "domestic",
    tagline: "White desert, lions and living crafts",
    hero: IMG.raj2,
    gallery: [IMG.wl3, IMG.raj1, IMG.raj5, IMG.raj6],
    overview:
      "Gujarat surprises: the Rann of Kutch's white salt desert under a full moon, Asiatic lions at Gir, the Statue of Unity and the temples of Somnath and Dwarka.",
    whyVisit: [
      "Rann Utsav white desert festival",
      "Only home of the Asiatic lion",
      "Somnath and Dwarka pilgrimage circuit",
      "World-class handicrafts and textiles",
    ],
    bestTime: "October – March",
    bestTimeNote: "October to March is cool and dry, coinciding with Rann Utsav and Navratri.",
    idealFor: ["Family", "Senior Citizens", "Friends", "Corporate", "Couples"],
    attractions: [
      { name: "Rann of Kutch", desc: "Endless white salt flats under moonlight." },
      { name: "Gir National Park", desc: "Asiatic lion safaris." },
      { name: "Statue of Unity", desc: "The world's tallest statue with viewing gallery." },
      { name: "Somnath & Dwarka", desc: "Two of India's most sacred temple towns." },
    ],
    experiences: [
      "Luxury tent stay at Rann Utsav",
      "Handicraft village trail in Bhuj",
      "Gir jeep safari with naturalists",
      "Sabarmati Ashram heritage walk",
    ],
    hotels: ["Luxury tented city at Dhordo", "Heritage palaces in Bhuj", "Resorts near Gir and Somnath"],
    related: ["rajasthan", "madhya-pradesh", "goa"],
  }),
  make({
    slug: "madhya-pradesh",
    name: "Madhya Pradesh",
    country: "India",
    region: "domestic",
    tagline: "The heart of India, wild and sculpted",
    hero: IMG.wl2,
    gallery: [IMG.wl4, IMG.wl5, IMG.raj2, IMG.raj6],
    overview:
      "Bandhavgarh and Kanha offer India's best tiger sightings, while Khajuraho's temples, Sanchi's stupa and Orchha's cenotaphs tell 2,000 years of art history.",
    whyVisit: [
      "Highest tiger density in India",
      "UNESCO sites at Khajuraho and Sanchi",
      "Marble rocks and Narmada river cruises",
      "Excellent luxury jungle lodges",
    ],
    bestTime: "October – April",
    bestTimeNote: "October to April is pleasant; March to May offers the strongest tiger sightings.",
    idealFor: ["Family", "Couples", "Friends", "Corporate", "Senior Citizens"],
    attractions: [
      { name: "Bandhavgarh National Park", desc: "Legendary tiger territory." },
      { name: "Kanha National Park", desc: "Sal forests that inspired The Jungle Book." },
      { name: "Khajuraho Temples", desc: "Masterpieces of Chandela sculpture." },
      { name: "Orchha", desc: "Riverside palaces and royal cenotaphs." },
    ],
    experiences: [
      "Core-zone tiger safari with expert naturalist",
      "Sound and light show at Khajuraho",
      "Boat ride at Bhedaghat marble rocks",
      "Heritage stay in Orchha",
    ],
    hotels: ["Luxury jungle lodges at Bandhavgarh & Kanha", "Heritage hotels in Orchha", "Resorts in Khajuraho"],
    related: ["rajasthan", "uttarakhand", "gujarat"],
  }),
  make({
    slug: "tamil-nadu",
    name: "Tamil Nadu",
    country: "India",
    region: "domestic",
    tagline: "Temple towers, hill stations and coastal calm",
    hero: IMG.raj6,
    gallery: [IMG.ker5, IMG.raj2, IMG.res4, IMG.ker3],
    overview:
      "Madurai's Meenakshi temple, the shore temples of Mahabalipuram, the blue hills of Ooty and the French quarter of Pondicherry make Tamil Nadu a deeply cultural and beautifully varied journey.",
    whyVisit: [
      "Some of India's grandest living temples",
      "Nilgiri Mountain Railway and hill stations",
      "Chettinad heritage mansions and cuisine",
      "Pondicherry's French colonial charm",
    ],
    bestTime: "October – March",
    bestTimeNote: "October to March is comfortable for the plains; hill stations are pleasant most of the year.",
    idealFor: ["Family", "Senior Citizens", "Couples", "Friends"],
    attractions: [
      { name: "Meenakshi Amman Temple, Madurai", desc: "Towering gopurams and vibrant ritual life." },
      { name: "Mahabalipuram", desc: "UNESCO shore temples and rock-cut reliefs." },
      { name: "Ooty & Coonoor", desc: "Tea gardens and the Nilgiri toy train." },
      { name: "Pondicherry", desc: "White Town streets, Auroville and seaside cafés." },
    ],
    experiences: [
      "Nilgiri Mountain Railway heritage ride",
      "Chettinad mansion stay and cooking session",
      "Temple heritage tour with a scholar guide",
      "Bharatanatyam performance evening",
    ],
    hotels: ["Heritage hotels in Chettinad", "Colonial resorts in Ooty", "Beach hotels in Mahabalipuram"],
    related: ["kerala", "karnataka", "odisha"],
  }),
  make({
    slug: "karnataka",
    name: "Karnataka",
    country: "India",
    region: "domestic",
    tagline: "Empires in stone, coffee in the hills",
    hero: IMG.raj1,
    gallery: [IMG.ker5, IMG.wl3, IMG.res4, IMG.raj2],
    overview:
      "Hampi's boulder-strewn ruins, Mysore's illuminated palace, Coorg's coffee estates and the Kabini wilderness combine heritage, nature and comfort in one exceptional circuit.",
    whyVisit: [
      "UNESCO ruins of the Vijayanagara Empire",
      "Coorg and Chikmagalur coffee plantations",
      "Kabini and Bandipur wildlife",
      "Mysore Palace illumination",
    ],
    bestTime: "October – March",
    bestTimeNote: "October to March offers ideal weather across heritage sites, hills and wildlife parks.",
    idealFor: ["Family", "Couples", "Honeymoon", "Friends", "Corporate"],
    attractions: [
      { name: "Hampi", desc: "A vast UNESCO landscape of temples and boulders." },
      { name: "Mysore Palace", desc: "Indo-Saracenic grandeur, spectacular after dark." },
      { name: "Coorg", desc: "Coffee estates, waterfalls and misty mornings." },
      { name: "Kabini", desc: "Backwater safaris for elephant and leopard." },
    ],
    experiences: [
      "Plantation bungalow stay in Coorg",
      "Coracle ride on the Tungabhadra at Hampi",
      "Kabini boat safari at golden hour",
      "Bengaluru corporate offsite and team building",
    ],
    hotels: ["Plantation resorts in Coorg", "Wildlife lodges at Kabini", "Heritage hotels in Mysore"],
    related: ["kerala", "tamil-nadu", "goa"],
  }),
  make({
    slug: "odisha",
    name: "Odisha",
    country: "India",
    region: "domestic",
    tagline: "Sacred coast, sculpted temples, tribal heartland",
    hero: IMG.ker4,
    gallery: [IMG.raj2, IMG.wl3, IMG.th4, IMG.ker5],
    overview:
      "Puri's Jagannath temple, Konark's sun chariot, Chilika's dolphins and the golden beaches of Gopalpur make Odisha a rewarding blend of pilgrimage, art and quiet coastline.",
    whyVisit: [
      "Jagannath Puri, one of the Char Dham",
      "Konark Sun Temple UNESCO heritage",
      "Chilika Lake dolphin and bird watching",
      "Distinctive Odissi dance and handloom traditions",
    ],
    bestTime: "October – March",
    bestTimeNote: "October to March is cool and dry — best for temples, beaches and Chilika boating.",
    idealFor: ["Family", "Senior Citizens", "Friends", "Couples"],
    attractions: [
      { name: "Jagannath Temple, Puri", desc: "One of Hinduism's four sacred Char Dham shrines." },
      { name: "Konark Sun Temple", desc: "A colossal stone chariot of the sun god." },
      { name: "Chilika Lake", desc: "Asia's largest brackish lagoon with Irrawaddy dolphins." },
      { name: "Udayagiri & Khandagiri", desc: "Ancient Jain rock-cut caves." },
    ],
    experiences: [
      "Sunrise at Puri beach",
      "Odissi dance performance evening",
      "Pipili appliqué and Raghurajpur craft village",
      "Chilika boat safari",
    ],
    hotels: ["Beach resorts in Puri and Gopalpur", "City hotels in Bhubaneswar", "Eco-retreats near Chilika"],
    related: ["north-east-india", "tamil-nadu", "madhya-pradesh"],
  }),
  make({
    slug: "golden-triangle",
    name: "Golden Triangle",
    country: "India",
    region: "domestic",
    tagline: "Delhi. Agra. Jaipur. India's greatest introduction.",
    hero: IMG.raj4,
    gallery: [IMG.raj3, IMG.raj1, IMG.raj6, IMG.raj5],
    overview:
      "The classic circuit — Mughal Delhi, the Taj Mahal at sunrise and the forts and bazaars of Jaipur. It remains the finest first journey through India and is easily extended into Ranthambore or Udaipur.",
    whyVisit: [
      "Three UNESCO World Heritage sites",
      "Perfect 5–7 day introduction to India",
      "Superb luxury hotels throughout",
      "Extends easily into Rajasthan or wildlife parks",
    ],
    bestTime: "October – March",
    bestTimeNote: "October to March keeps sightseeing cool and comfortable across all three cities.",
    idealFor: ["Family", "Couples", "Honeymoon", "Senior Citizens", "Friends", "Corporate"],
    attractions: [
      { name: "Taj Mahal, Agra", desc: "Sunrise viewing of the world's most beautiful monument." },
      { name: "Amber Fort, Jaipur", desc: "Hilltop fortress with mirrored halls." },
      { name: "Qutub Minar & Humayun's Tomb", desc: "Delhi's UNESCO Mughal legacy." },
      { name: "Agra Fort", desc: "Red sandstone citadel overlooking the Yamuna." },
    ],
    experiences: [
      "Private sunrise Taj Mahal visit",
      "Old Delhi rickshaw and food walk",
      "Jaipur block-printing and gem workshop",
      "Luxury Gatimaan Express rail transfers",
    ],
    hotels: ["Palace hotels in Jaipur", "Taj-view hotels in Agra", "Luxury five-star hotels in Delhi"],
    related: ["rajasthan", "madhya-pradesh", "uttarakhand"],
  }),
];

export const bySlug = (slug: string) => destinations.find((d) => d.slug === slug);
export const primeDestinations = destinations.filter((d) => d.prime);
export const internationalDestinations = destinations.filter((d) => d.region === "international");
export const domesticDestinations = destinations.filter((d) => d.region === "domestic");
export const internationalSorted = [
  ...internationalDestinations.filter((d) => d.prime),
  ...internationalDestinations.filter((d) => !d.prime).sort((a, b) => a.name.localeCompare(b.name)),
];
