import type { Metadata } from "next";
import { Sitemap } from "@/views/Utility";
import { buildMetadata } from "@/lib/seo";

/**
 * Human-readable sitemap. The machine-readable XML lives at /sitemap.xml
 * and is generated by app/sitemap.ts.
 */
export const metadata: Metadata = buildMetadata({
  title: "Sitemap",
  description:
    "A complete index of every page on the Royal Rajasthan Holidays website.",
  path: "/sitemap-page",
});

export default function Page() {
  return <Sitemap />;
}
